package backend.auth;

public enum UserRole {
	ADMIN,
	ADMIN_PROJECT_MANAGER,
	PROJECT_MANAGER,
	SITE_ENGINEER,
	FIELD_WORKER,
	CLIENT,
	CLIENT_BUILDING_OWNER,
	MATERIAL_SUPPLIER,
	FINANCE_OFFICER_ACCOUNTANT
}
